### ISSUE TITLE
Process hanging in latest minor version v6.1

### ISSUE THREAD

**Issue by srilq** [brightcove/hot-shots#100]
Since upgrading to v6.1 from v6.0 the process hangs forever, preventing our tests from exiting.

This might be related to #57 but this issue has only cropped up more recently for us.

### Previous Behaviour

Calling `client.close()` after all tests finish prevents the process from hanging.

### Current Behaviour

Calling `client.close()` seems to have no effect.

**Comment by srilq** [comment]
Possibly related to #93.

**Comment by bdeitte** [comment]
Huh, that's interesting that this just started happening.  I am going to fold this into https://github.com/brightcove/hot-shots/issues/57 and add some comments there.
