### ISSUE TITLE
Tags not being sent

### ISSUE THREAD

**Issue by buianhthang** [brightcove/hot-shots#102]
Hi,

I'm using `hot-shots` with DogStatsD for my application. When I using tags with the syntax same as mentioned, I cannot find tags which I tagged in Datadog Metrics (only found globalTags)

```
const StatsD = require('hot-shots')

const dogStatsd = new StatsD({
    host: myhost,
    port: 8125,
    globalTags: {
        env: 'development',
        errorHandler: err =>
            console.log(`Encountered an error with Statsd: ${err}`)
    }
})

// Incrementing with tags
dogStatsd.increment('my_counter', ['foo', 'bar'])

dogStatsd.increment('my_counter', {
    foo: 'bar'
})
```

<img width="477" alt="image" src="https://user-images.githubusercontent.com/10458061/53505606-bed48a80-3ae6-11e9-927e-a93120f8ed23.png">

**Comment by bdeitte** [comment]
I can see that the general case of calling increment like this is working, as we have a test on this: https://github.com/brightcove/hot-shots/blob/master/test/statsFunctions.js#L186

Could you try taking out the global tags and see if that fixes it?  Perhaps there is an unknown bug there?  Also you should have the errorHandler out of your global tags, like this:  
```
const dogStatsd = new StatsD({
    host: myhost,
    port: 8125,
    globalTags: {
        env: 'development'
    },
    errorHandler: err =>
        console.log(`Encountered an error with Statsd: ${err}`)
})
```

**Comment by buianhthang** [comment]
@bdeitte I'm trying to create dogStatsd one time only, then I just need to increase counter key with tags where I need. But only global tags at creation time available here. I'm expecting new tags added at increase time should be there.

I will need to look into your test again.

**Comment by buianhthang** [comment]
@bdeitte now I can use `hot-shots` as my expectation. thank you.
