### ISSUE TITLE
Support configuring the client from environment variables

### ISSUE THREAD

**Issue by ahmed-mez** [brightcove/hot-shots#103]
All of the official Datadog dogstatsd clients can now be configured via standard environment variables.  As the maintainer of the node dogstatsd library, could you port the same functionality to this client?  We would prefer that configuration be consistent across client libraries.

Sample changes from the Go implementation can be found here: https://github.com/DataDog/datadog-go/pull/78

Let me know if you have any questions about the code or the feature more generally.

Thanks,

Ahmed

**Comment by bdeitte** [comment]
Hi @ahmed-mez thanks for the request!  As the one person who has been maintaining this library, I do make updates when I can, but I can't guarantee any porting myself.  I do though promptly review and merge in any changes made, so happy to do so if anybody wants to make them.

**Comment by ahmed-mez** [comment]
Hi @bdeitte, I've submitted a PR https://github.com/brightcove/hot-shots/pull/105 to add the feature, I'll be looking forward to get a review and I'll be happy to make changes if needed.

Thanks!

**Comment by bdeitte** [comment]
Thanks, merged in!  Switched phones and getting two-factor auth set up properly again here, but I'll get a new build published soon with this in it.
