### ISSUE TITLE
increment and decrement functions handle their arguments inconsistently which result in an unexpected decrement behavior

### ISSUE THREAD

**Issue by lbeschastny** [brightcove/hot-shots#117]
Right now `.increment` and `decrement`  functions handle their arguments inconsistently.

`.increment` could called with measurement name and tags object, but without an explicit value:

```js
client.increment(measurementName, tags);
```

But any attempt to use `.decrement` in the same way results in tags not being sent.

This behavior is caused by #33 where `.increment` was specifically modified to handle calls without `value` argument, while `.decrement` was left untouched.

**Comment by bdeitte** [comment]
This should be fixed in 6.5.0- let me know if you see any issues here
