### ISSUE TITLE
AWS Lambda use case

### ISSUE THREAD

**Issue by runk** [brightcove/hot-shots#126]
My org uses hot-shots almost everywhere, except serverless functions namely AWS Lambdas. Reason for that is there's no local datadog agent where to connect. Instead, there's expectation that app would print metrics to stdout in standard format like

```
MONITORING|my.metric.name|#tag1:value,tag2
```

Would you accept a PR where I'd add support of stdout as alternative "transport", maybe via another `protocol` setting type?

**Comment by bdeitte** [comment]
I didn't realize that's how AWS lambdas did this, that's interesting!  As another protocol, that makes sense and would be fine with me.

**Comment by bdeitte** [comment]
Fixed with https://github.com/brightcove/hot-shots/pull/130

**Comment by vvo** [comment]
Just in case someone is looking at this: I wasn't able to use this directly for Datadog + AWS lambda. As it needs some prefixes. The format for Datadog to output on the console is either:

```js
{
    "m": "Metric name",
    "v": "Metric value",
    "e": "Unix timestamp (seconds)",
    "t": "Array of tags"
}
```

or

```
MONITORING|<UNIX_EPOCH_TIMESTAMP>|<METRIC_VALUE>|<METRIC_TYPE>|<METRIC_NAME>|#<TAG_LIST>
```

There's one catch: you can only use distribution metrics. As explained here: https://docs.datadoghq.com/serverless/custom_metrics/#understanding-distribution-metrics

In the end, I went for the recommended Datadog way:

```js
import { sendDistributionMetric } from 'datadog-lambda-js';

sendDistributionMetric(
    'coffee_house.order_value', // Metric name
    12.45,                      // Metric value
    'product:latte',            // First tag
    'order:online'              // Second tag
);
```

Good luck!
