### ISSUE TITLE
Handle issues with udsGracefulErrorHandling 

### ISSUE THREAD

**Issue by bdeitte** [brightcove/hot-shots#128]
See https://github.com/brightcove/hot-shots/pull/123#issuecomment-537674855.  It appears we need to handle more error cases for retries.

**Comment by msiebuhr** [comment]
Shouldn't we just try re-connecting on all of them.

And a important detail I noticed: Error-codes are *negative*. My code sees -102, -107 and -111.

**Comment by bdeitte** [comment]
@msiebuhr I see your comments in https://github.com/brightcove/hot-shots/issues/114#issuecomment-540548105 as well so making this a more generic ticket on potential issues with this feature.  Also interesting on what you see for codes, as it's different than what @alessio-modus mentions in https://github.com/brightcove/hot-shots/pull/123

**Comment by pcothenet** [comment]
We're experiencing something like #114. When the agent restart, hot-shots never seem to reconnect properly (error -107)

**Comment by dhermes** [comment]
I'm currently looking into this as well. (I'll probably update this post as I go.) I've got a `local-dd-agent` Docker container / host UDS I've been using to reproduce this.

Error codes:

- 102 / [0x66][3] (Linux): `ENETRESET`
- 107 / [0x6b][4] (Linux): `ENOTCONN`
- 111 / [0x6f][5] (Linux): `ECONNREFUSED`
- 54 / [0x36][2] (macOS): `ECONNRESET`, happens only on the **first** failure when UDS is deleted
- 39 / [0x27][1] (macOS): `EDESTADDRREQ`, happens for **every** attempt to send after deleting the initial UDS (even if a new file replaces it)

[1]: https://github.com/golang/go/blob/go1.15.2/src/syscall/zerrors_darwin_amd64.go#L1157
[2]: https://github.com/golang/go/blob/go1.15.2/src/syscall/zerrors_darwin_amd64.go#L1155
[3]: https://github.com/golang/go/blob/go1.15.2/src/syscall/zerrors_linux_amd64.go#L1272
[4]: https://github.com/golang/go/blob/go1.15.2/src/syscall/zerrors_linux_amd64.go#L1296
[5]: https://github.com/golang/go/blob/go1.15.2/src/syscall/zerrors_linux_amd64.go#L1228

**Comment by dhermes** [comment]
So here is a summary of the problems with the current implementation:

1.  If `this.socket` doesn't get created on start (as a UDS) then it will **never** recover (even if the UDS eventually gets fixed / recreated). This can be addressed by attempting to re-create a socket in `sendMessage()` https://github.com/brightcove/hot-shots/blob/c488cc77abe0a4edcbc68494c1d28fbd9d84ed70/lib/statsd.js#L357
1.  As mentioned above the list of `errno` codes are platform-specific to Linux (https://github.com/brightcove/hot-shots/blob/c488cc77abe0a4edcbc68494c1d28fbd9d84ed70/lib/statsd.js#L128-L129), I recommend ditching the switch statement for a recommend doing something like `errorCodes.includes(-err.code)` with `errorCodes` produced by
    ```js
    function udsErrors() {
      if (process.platform == 'linux') {
        return [
          os.constants.errno.ENOTCONN,
          os.constants.errno.ECONNREFUSED,
        ]
      }
    
      if (process.platform == 'darwin') {
        return [
          os.constants.errno.EDESTADDRREQ,
          os.constants.errno.ECONNRESET,
        ]
      }
    
      // Unknown / not yet implemented
      return []
    }
    ```
1.  When a new socket is created in the UDS recovery code (https://github.com/brightcove/hot-shots/blob/c488cc77abe0a4edcbc68494c1d28fbd9d84ed70/lib/statsd.js#L136) it doesn't re-register socket error handling code, so this means a UDS failure can only be recovered from one time

I'll send a PR with fixes for all 3 but this may be a longer discussion
