### ISSUE TITLE
Change metric name from value when using Telegraf

### ISSUE THREAD

**Issue by jordanpurinton** [brightcove/hot-shots#134]
When you send a metric, the default field key is `value`. Is there a way to change that?
So if I wanted to send a metric called `http`, I could have a field key called `errors` and another called `connections` or whatever.

**Comment by bdeitte** [comment]
I'm not sure I understand here- can you give an example call where you see this and share where the data is sent (Datadog, statsd, etc).

**Comment by jordanpurinton** [comment]
So I'm sending to Telegraf which outputs to Influx. I've attached what I see in Grafana, for reference. Basically I want to change the tag key from `value` to another name. 

![Capture](https://user-images.githubusercontent.com/12102971/67344032-f7592680-f504-11e9-8814-2aba7edb7f65.PNG)

**Comment by bdeitte** [comment]
I don't know where the "value" comes from- I assume that's something from Telegraf.  There is only a way to send one metric value at a time- you can add tags to this one value but this appears to be sending on multiple values.  If there is some addition to the protocol that is Telegraf-specific, we can keep this ticket open and wait for someone to work on it.  Unfortunately I am not very familiar with it myself.

**Comment by jordanpurinton** [comment]
Oh ok, that's fine then. Just was wondering if there was something from your end that could be fixed. Probably requires me to do some more digging on my own. I'll do that and will close this issue.

**Comment by mariotacke** [comment]
@jordanpurinton, trying to do the same right now. Did you ever find a way to do so? From the code, it looks like hot-shots does not support telegraf field sets (only tag sets) based on the spec: https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/.
