### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by cookrn** [brightcove/hot-shots#146]
After upgrading to 6.8.4 with the changes from #143, I'm seeing the error in the title on this line: `this.socket.on('error', options.errorHandler);` (location: `lib/statsd.js:113:17`)

We use the TCP protocol and often run with no server present meaning the socket fails to connect.

Is this supported behavior?

Thanks in advance for any guidance!

**Comment by cookrn** [comment]
FWIW, our library version was upgraded and merged automatically by Dependabot because it was a patch version change.

**Comment by bdeitte** [comment]
Shoot, that does look like a bug!  Trying to see how to fix it, should be able to patch it tonight.

**Comment by bdeitte** [comment]
Thanks for pointing this out.  Fixed in 6.8.5

**Comment by cookrn** [comment]
@bdeitte thanks for being so responsive -- we appreciate your work on hot-shots!
