### ISSUE TITLE
A missing check for socket existence 

### ISSUE THREAD

**Issue by ralphiech** [brightcove/hot-shots#179]
I noticed A missing check for socket existence in two places (lib/statsd.js:109 and (lib/statsd.js:122)

I can give details or push a fix (if you grant me permission)

**Comment by bdeitte** [comment]
@ralphiech Please feel free to open a PR for any fix, and I can look at it and merge in if all looks good.  Thanks, appreciate it!

**Comment by ralphiech** [comment]
https://github.com/brightcove/hot-shots/pull/182
