### ISSUE TITLE
Error handler not honored

### ISSUE THREAD

**Issue by ralphiech** [brightcove/hot-shots#180]
I noticed a place where the custom error handler is not honored (lib/statsd.js:359)

I can give details or push a fix (if you grant me permission)

**Comment by bdeitte** [comment]
@ralphiech Here as well, please feel free to open a PR for any fix, and I can look at it and merge in if all looks good.  Thanks, appreciate it!

**Comment by ralphiech** [comment]
https://github.com/brightcove/hot-shots/pull/183
