### ISSUE TITLE
percentile for timing() method

### ISSUE THREAD

**Issue by ckshobha** [brightcove/hot-shots#181]
I have an issue where the 50th, 75th and 90th percentiles received all have the same value for the duration. 
and datadog engineers informed that the data aggregation happens for 10 sec flush window.  They did mention that this time cannot be changed.

But checking to see if bufferFlushInterval and maxBufferSize would in any way be used for percentile aggregation? Could some one help me with this? Thanks in advance for your time.

**Comment by bdeitte** [comment]
maxBufferSize is set to 0 by default, which means that metrics are sent on every metric.  So if you're not setting this, then everything should be sent to DogStatsD every time something is sent.  Not sure exactly what the issue would be here.

**Comment by bdeitte** [comment]
Closing this out since I didn't hear anything more on this.
