### ISSUE TITLE
Use strict

### ISSUE THREAD

**Issue by ash2k** [brightcove/hot-shots#19]
I noticed `'use strict';` is missing from `.js` files. It might be safer to use strict mode, WDYT?

**Comment by bdeitte** [comment]
Certainly, missed that this wasn't there!  I'll put this in sometime soon, or feel free to add it to your PR (which I should get to review later today, thank you for that).

**Comment by ash2k** [comment]
I didn't add it to my PR because there were some test failures because of it and I didn't have time to look into it.

**Comment by bdeitte** [comment]
Huh, very interesting.  I should be able to take a look at this another day.
