### ISSUE TITLE
[Help needed] Submitting RATE metric

### ISSUE THREAD

**Issue by glebskalinskii** [brightcove/hot-shots#190]
From the docs it's not clear if it's possible to submit [RATE metric](https://docs.datadoghq.com/developers/metrics/types/?tab=rate#metric-types)

Can someone please help to figure out if it's possible and how to do it?

**Comment by bdeitte** [comment]
You can not set rate directly with DogStatsD that hot-shots works with, as is noted on the bottom of that page.  You can though have rates that are shown in Datadog through a histogram as shown on that page as well.  Hope that helps.
