### ISSUE TITLE
how to restrict local port range when sending udp

### ISSUE THREAD

**Issue by davehorton** [brightcove/hot-shots#192]
I am sending stats to Telegraf via udp and have noticed that hot-shots binds to a fairly large number of open ports.  That is not an issue, so long as I can somehow give it a local port range to use -- as it is, it is binding to ports that another process on the machine needs to have and thus causing some failures in my application when this other software fails to grab a port which it believes should be free.

Is there a config property to specify what local udp port range to restrict to?  And why is it using so many local ports in any case?

**Comment by bdeitte** [comment]
Hi @davehorton that's interesting, haven't heard of this one before.  hot-shots is just using default behaviors in https://nodejs.org/api/dgram.html in general.  There's no config currently for range, but I wonder if using the "port" config would work for this case?

**Comment by bdeitte** [comment]
I don't think there's anything we'll be doing here other than the existing port config so closing out.
