### ISSUE TITLE
Flag to disable DD_ENTITY_ID globalTag behavior

### ISSUE THREAD

**Issue by laupow** [brightcove/hot-shots#203]
`hot-shots` needs a toggle to disable this default DD_ENTITY_ID behavior:

>  The Datadog dd.internal.entity_id tag is appended to globalTags from the DD_ENTITY_ID environment variable if the latter is set

One of our metrics databases was recently overloaded with excessive cardinality because the library starting tagging metrics in a non-Datadog metric pipeline. 

Datadog was enabled on the the application. However, most application metrics went to an Influx database (not Datadog) but still had the `DD_ENTITY_ID` tag. Combined with all our other tags, the database exploded with cardinality. 

We did not expect `hot-shots` to be automatically add this metrics tag.

**Comment by bdeitte** [comment]
Hi @laupow sorry to hear that and thanks for entering the issue.  Note that all hot-shots PR are community-driven at this point, so if you'd like to see this in there, consider creating a PR for it.  Thanks.
