### ISSUE TITLE
Child client should override matching tags

### ISSUE THREAD

**Issue by ash2k** [brightcove/hot-shots#22]
If parent client already has some global tags, client's tags should override tags with same name (case-sensitive?).

**Comment by bdeitte** [comment]
It would make sense to me to override here.  What were you considering on this one?

**Comment by ash2k** [comment]
I'm sorry, I don't understand the question. Could you explain what you mean?

**Comment by bdeitte** [comment]
I was wondering how you expected things to happen with this and case-sensitivity.  Since you are likely the one person using this feature right now, your opinion matters!

**Comment by ash2k** [comment]
I'll just submit a PR for review for this when I'll have some time. Cheers!
