### ISSUE TITLE
Cache DNS implementation is susceptible to a stampede

### ISSUE THREAD

**Issue by hjr3** [brightcove/hot-shots#223]
First, thank you for making this client. It has been very useful.

At $JOB, we have a load bearing service sending stats via this client. One challenge is that we are on k8s, which has some real problems. See [Racy conntrack and DNS lookup timeouts](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts). Ideally, we should use [NodeLocal DNSCache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) but for $REASONS we have not made that change.

We have seen [dns.lookup](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback) take multiple  seconds due to this. Our collector rarely changes its IP address, so caching the results is a natural solution.

Recently, I was noticing hundreds of calls to `dns.lookup` in our traces and tracked it down to:

https://github.com/brightcove/hot-shots/blob/02f26a6d5da6fd2351404afc39c45836a1f017f5/lib/transport.js#L56-L71

Let us assume:

- the service is sending one stat every 1ms
- `dns.lookup` takes 100ms to respond

When we cache miss, we will make roughly 100 calls to `dns.lookup` before one call succeeds and we updated `dnsResolutionData` with the results. When combined with the above k8s DNS issues, each subsequent call to `dns.lookup` exacerbates the issue and we balloon to multi-second DNS lookups.

The solution I have implemented internally uses the stale IP address until the next DNS lookup succeeds. Would you be open to such a patch? My use case is a bit unique, but it does seem like folks may want to opt-in to that behavior as the `dns.lookup` call is not really asynchronous.

> DNS requests in node appear asynchronous, but they're actually internally implemented as synchronous calls within node's internal libuv threadpool (which by default has only 4 threads). That means if you do >4 DNS lookups in parallel then you're going to block the libuv threadpool

Source: https://httptoolkit.tech/blog/configuring-nodejs-dns/

**Comment by hjr3** [comment]
Actually, maybe the best path forward is exposing a function that allows a custom DNS lookup. It would be passed in as the lookup` option in: https://nodejs.org/api/dgram.html#dgramcreatesocketoptions-callback

**Comment by bdeitte** [comment]
Sorry for the slow response on this, and an interesting issue.  I think either of your solutions here is reasonable as an option and would accept a patch for this.  Thanks.
