### ISSUE TITLE
[feature-request] Noop/Console implementation

### ISSUE THREAD

**Issue by juzerali** [brightcove/hot-shots#225]
For the cases where application needs to be run in multiple environments where a statsd server may not be available, provide Noop and Console implementations that just ignores or logs the method calls on console respectively.

**Comment by bdeitte** [comment]
Sounds like a good idea.  As a heads up, no one is fixing any of the issues that come up here- this is all community driven.  So if you are interested in doing this, please feel free.

**Comment by tmcdonnell87** [comment]
@juzerali would this work for you?
```
export default new StatsD({
  protocol: 'stream',
  stream: process.stdout,
});
```

**Comment by ehaynes99** [comment]
For a no-op version, you could do:
```typescript
import { Writable } from 'node:stream'

new StatsD({
  protocol: 'stream',
  stream: new Writable({
    write: (_chunk, _encoding, callback) => callback,
  }),
})
```

**Comment by bdeitte** [comment]
Simple stream solution makes sense, closing out

**Comment by ehaynes99** [comment]
Blast from the past, but I just realized that I was missing the parenthesis on the `callback()` part of that example. Edited and fixed.
