### ISSUE TITLE
StatsD ClientOptions interface is missing `stream` property

### ISSUE THREAD

**Issue by albert-mirzoyan** [brightcove/hot-shots#233]
The runtime supports the `stream` option
https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L64
But the types.d.ts is missing the declaration.
https://github.com/brightcove/hot-shots/blob/master/types.d.ts#L5

**Comment by bdeitte** [comment]
Thanks for the heads up.  PRs are always welcome, or I'll try to remember this the next time I'm merging things and making updates.

**Comment by bdeitte** [comment]
I am making a small update myself right now, and I was going to put this in.  But I'm not using TypeScript and wasn't 100% sure the type should  be Stream.  So until next time I make a change, or someone else can submit the PR.
