### ISSUE TITLE
Increment/decrement gauge values?

### ISSUE THREAD

**Issue by half0wl** [brightcove/hot-shots#248]
Does this library support incrementing/decrementing gauge values?

https://github.com/statsd/statsd/blob/master/docs/metric_types.md#gauges specifies that a gauge can accept a sign for changing the value:

```
gaugor:-10|g  # Decrement 10
gaugor:+4|g  # Increment 4
```

However, the type signature of `gauge` here seem to only accept `number` as a value:

https://github.com/brightcove/hot-shots/blob/b4422446831b47873637b43ff6d111b1cef1b5d5/types.d.ts#L125-L128

**Comment by bdeitte** [comment]
This has now been done in https://github.com/brightcove/hot-shots/pull/259
