### ISSUE TITLE
Question: What is the recommended lifetime of a client?

### ISSUE THREAD

**Issue by MikeOBarometer** [brightcove/hot-shots#249]
The example mentions this about close

```
  // Close statsd.  This will ensure all stats are sent and stop statsd
  // from doing anything more.
  ```

Are stats not sent until we close? What is the recommended lifetime for a client? Should it live as long as the service does OR should it be created/closed as needed?

**Comment by bdeitte** [comment]
clients can live as long as needed- this just means that any stats that are outstanding are sent
