### ISSUE TITLE
increment, decrement, etc in lib/statsFunctions don't use enqueue—is this intentional?

### ISSUE THREAD

**Issue by KelWill** [brightcove/hot-shots#254]
The functions in https://github.com/brightcove/hot-shots/blob/master/lib/statsFunctions.js call `sendAll` rather than `enqueue`, bypassing any buffering. Is that intentional? It surprised my team—until we profiled it carefully, we thought that setting `maxBufferSize` meant that we were buffering our stats sends.

Would you be open to a PR reworking those statsFunctions to use enqueue? Alternatively, I'd be happy to open up a PR that updates language in the README to hopefully align more closely to how `maxBufferSize` and such are supposed to work.

**Comment by mm-zacharydavison** [comment]
They ultimately call [this](https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L266) `_send` function, which does in fact enqueue.

**Comment by KelWill** [comment]
Sorry for the bad report!
