### ISSUE TITLE
You need to get on DataDogHQ Libraries page

### ISSUE THREAD

**Issue by zentuit** [brightcove/hot-shots#27]
I've been looking for a dogstatd node client that supports events. None of the one's listed on http://docs.datadoghq.com/libraries/ seem to support events without using the http api.

It was only through looking at node-dogstatsd pull request that I found this project.

**Comment by bdeitte** [comment]
Yeah I emailed someone on Datadog a long time ago on this, through some newsletter that told me who to email to get on this page.  Never heard back, and I've forgotten about it since then.  I'll try  code@datadoghq.com as I see on that page now.  Thanks for the reminder!

**Comment by irabinovitch** [comment]
@zentuit @bdeitte Thanks for the heads up. We'll go ahead and get this added.

**Comment by bdeitte** [comment]
@irabinovitch that was quick, thank you!
