### ISSUE TITLE
`unix-dgram` errors when building with Node 22

### ISSUE THREAD

**Issue by danielfigueiredo** [brightcove/hot-shots#278]
Hey folks 👋 , 

I've updated to latest LTS Nodejs (22.X.X) stable release, and now I can't get rid of the V8 errors that comes from `unix-dgram`. The reason why I'm posting this here, is because `hot-shots` is the only reason why `unix-dgram` is in my dependency tree.

It is concerning to me that `unix-dgram` hasn't [received a commit](https://github.com/bnoordhuis/node-unix-dgram/commits/master/) in 2 years and thus haven't made changes to support the new V8. Are there plans to migrate to another library or to patch `unix-dgram`? 

Although these errors _don't_ necessarily cause `yarn` to exit with code `1` and block installs or CI, they are very misleading and often make people waste time. An example log:

```sh
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../src/unix_dgram.cc:5:
../../nan/nan.h:2548:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/dfigueiredo/Library/Caches/node-gyp/22.11.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
  void SetAccessor(
       ^
/Users/dfigueiredo/Library/Caches/node-gyp/22.11.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
  void SetAccessor(
       ^
In file included from ../src/unix_dgram.cc:5:
../../nan/nan.h:2594:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/dfigueiredo/Library/Caches/node-gyp/22.11.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
```

To confirm `hot-shots` is the only library dependency on `unix-dgram` in our whole monorepo:

```sh
yarn why unix-dgram

[1/4] 🤔  Why do we have the module "unix-dgram"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "unix-dgram@2.0.6"
info Reasons this module exists
   - "_project_#@ourorg#backstage-plugin-pkgname-backend#@ourorg#pkgname#hot-shots" depends on it
   - Hoisted from "_project_#@ourorg#backstage-plugin-pkgname-backend#@ourorg#pkgname#hot-shots#unix-dgram"
```

(Just updated the org and pkgs names that cannot be disclosed)

Any insights here would be helpful and inform our roadmap 🙏 . The easiest for us would be to keep using `hot-shots` and this problem gets patched upstream, otherwise we wouldn't have many options other than ejecting and looking for an alternative.

Thanks all!

**Comment by bdeitte** [comment]
Hi there, when I've looked in the past ,I haven't found any libraries that implement unix-dgram. If anybody else knows of one that could work better, let me know. This has also been discussed in Node.js, since dgram support was removed at one point from Node.js, and it's been closed more than once as something that won't be redone there.  https://github.com/nodejs/node/issues/29339  "I'm the author of node-unix-dgram and its usage is light enough that I don't think unix_dgram is missed all that much."

So I believe the best action here is to open your concerns against unix-dgram, and I'd be happy to pull in a new version if something is fixed there.

**Comment by danielfigueiredo** [comment]
Thanks @bdeitte !

I tried looking around, and I couldn't find anything, in fact I would expect this to be part of Nodejs as well 😞 
But makes sense not to be there after reading the issue you linked

I've opened a similar issue on `unix-dgram`, let's see what they say!

**Comment by bdeitte** [comment]
Closing given the conversation in https://github.com/bnoordhuis/node-unix-dgram/issues/62
