### ISSUE TITLE
close callback never invoked in some cases

### ISSUE THREAD

**Issue by thesmart** [brightcove/hot-shots#30]
I have noticed that if no socket connection is ever opened, then the callback passed to the close method is never invoked.  This leads to my app being hung, waiting forever for the close callback.  
If the connection is already in a state of closed, then the callback should be invoked immediately because the callback is a signal that the closed state has been reached.  

Otherwise, if we don't think the callback should be invoked because the socket was never opened and therefore cannot be closed, then the close method as-it-is is not idempotent. So, it should probably throw a new Error to indicate that the connection was never opened and therefore cannot be closed.

I would consider either solution to be a "resolution".  What do you guys think?

I am running node v4.3.2.

**Comment by thesmart** [comment]
Hmm, having a hard time reproducing this issue.  Closing until I can.

**Comment by bdeitte** [comment]
If you do keep running into this in production, even if you can't reproduce in a simple case, feel free to reopen this.  I don't mind keeping it open for awhile to see if others have run into this.
