### ISSUE TITLE
No `error` listener is added to the udp socket

### ISSUE THREAD

**Issue by ggoodman** [brightcove/hot-shots#31]
Running `hot-shots` in production in a kubernetes environment results in sporadic dns lookup failures for me. As there is no `error` listener attached to the socket my hypothesis is that dns lookup errors are bubbling their way up as uncaught exceptions, resulting in a server crash.

Request: Use the existing `options.errorHandler` for:

```js
if (options.errorHandler) {
  this.socket.on('error', options.errorHandler);
}
```

**Comment by bdeitte** [comment]
Thanks for the suggestion- you're welcome to open a PR for this, sounds like a good idea to me.

Another thing you may want to do is set cacheDns so that the host lookup is only done once.

**Comment by ggoodman** [comment]
@bdeitte thanks for the suggestion re: `cacheDns`. Unfortunately as services can move around within a cluster, relying on a cached ip address would just accelerate the service's race to the grave ;-)

I'll put a PR on the backlog.
