### ISSUE TITLE
Child Prefixes

### ISSUE THREAD

**Issue by zz85** [brightcove/hot-shots#35]
Shouldn't prefix add on to the parent's eg.

```js
parent.prefix + (options.prefix || '')
```

instead of

```js
(options.prefix || '') + parent.prefix
```

in https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L559
?

**Comment by bdeitte** [comment]
I think an argument could be made in either order.  Unfortunately I don't think that we could change this- doing that would break anyone already using this functionality without a very clear benefit.  I'm going to close this issue, but let me know if I am missing something here.  Thanks.

**Comment by jnv** [comment]
I was surprised by this behavior too. Perhaps there could be some additional property for child which would append the child's prefix to parent's? Ideas for name: `subPrefix`, `childPrefix`, `appendPrefix`

**Comment by rasmuslp** [comment]
This surprised me as well. However, a simple solution is to set it manually on the child:
```JS
child.prefix += 'child-prefix-that-comes-after-parent';
```
