### ISSUE TITLE
global prefix is not concatated for "check" function

### ISSUE THREAD

**Issue by shmuelgutman** [brightcove/hot-shots#38]
Hi,
Thanks for this library, very useful.
calling "check" function like this:
`client.check('service.running', this.CHECKS.OK, [this.serviceName]);`
with global prefix param set to "somePrefix." 
I would expect the data sent to Datadog to be named as "somePrefix.service.running" like happends in other functions but isn't.

**Comment by bdeitte** [comment]
That does make sense, sounds like a bug!  I'll leave this open until it's fixed.  Thanks for the note.

**Comment by bdeitte** [comment]
And sure enough you can see that in the non-check case the prefix/sufix is used:

https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L204

But the stat in the check case doesn't use this:

https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L387

Should be simple enough for someone to fix!
