### ISSUE TITLE
dgram Error: Not running

### ISSUE THREAD

**Issue by emmanuelbuah** [brightcove/hot-shots#39]
Running into this error sometimes due to the forced closed socket connection when a work disconnect or closes in a cluster. I dug around a bit and found this - https://github.com/phuesler/ain/issues/24 which elaborates on this issue with dgram.

**Comment by bdeitte** [comment]
The linked issue reads to me like it's an issue there with the server side of a socket connection- am I reading that right?  In that case it's an issue with whatever you are connecting to.  If you don't think it's that, I'll certainly keep this open  And if that linked issue is suggesting a fix that can be made here, please feel free to submit a PR.  Thanks!

**Comment by bdeitte** [comment]
Closing this, given what I mention above.  Please let me know if this is in error.  Thanks.
