### ISSUE TITLE
Error sending hot-shots message: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

### ISSUE THREAD

**Issue by slossgaming** [brightcove/hot-shots#47]
I get the error: "Error sending hot-shots message: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running" When attempting to send a request to DataDogHQ

**Comment by bdeitte** [comment]
This sounds like you don't have the Datadog agent running.  See https://docs.datadoghq.com/guides/dogstatsd/#setup

**Comment by bdeitte** [comment]
Closing this, but feel free to reopen if you need help.

**Comment by luqmaan** [comment]
I was getting the `Error sending hot-shots message: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running` error a lot as well.

I had DataDog correctly installed and it was successfully reporting other metrics.

```
/var/log/datadog/dogstatsd.log

2017-12-28 15:29:22 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:451) | Error receiving datagram `request.started:hostname:commerce-api.nike.com|c`
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 439, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 617, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 469, in parse_metric_packet
    raise Exception(u'Unparseable metric packet: %s' % packet)
Exception: Unparseable metric packet: request.started:hostname:commerce-api.nike.com|c
```

I think there may be a bug around parsing arguments when there are tags and a callback.

```
client.histogram('request.active_count', 3, ['hostname:commerce-api.nike.com'], callback)
```

For now, I'm working around it by always explicitly sending the `sampleRate` argument.


```
client.histogram('request.active_count', 3, 1, ['hostname:commerce-api.nike.com'], callback)
```

This might be related to https://github.com/brightcove/hot-shots/issues/33 https://github.com/brightcove/hot-shots/pull/42.

**Comment by bdeitte** [comment]
@luqmaan That does sound very much like the increment issue- the optional arguments setup in node-statsd/hot-shots has always been a little... suspect.  If you're feeling sure it's solved by the sampleRate addition and you're on the latest version, could you open a new issue on this?
