### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by bdeitte** [brightcove/hot-shots#48]
Add back typescript typings as noted in https://github.com/brightcove/hot-shots/pull/46 Making an issue in case @jgwmaxwell doesn't get to it, or if that does happen assigning the hacktoberfest label so he can get credit for it if he wants.  :)

**Comment by karsai5** [comment]
In order to get the typescript definitions to work I had to change the module export. I've created a pull request at https://github.com/brightcove/hot-shots/pull/54
