### ISSUE TITLE
[Feature Request] support async functions for client.timer

### ISSUE THREAD

**Issue by tzvipm** [brightcove/hot-shots#66]
Currently, client.timer works only for synchronous code. I think it would be nice to allow the input function to return a promise and then run the metrics after the promise resolves. This would also allow for async functions to me measured using the `client.timer` API.

If you think this is a good idea, I'd be happy to put up a PR for it.

**Comment by bdeitte** [comment]
That sounds like a great idea to me- I would accept a PR for that.  Thanks!
