### ISSUE TITLE
Add support for TCP connections

### ISSUE THREAD

**Issue by honzajavorek** [brightcove/hot-shots#76]
Thanks for this library! It took me a while to stumble upon it (not really intuitive name, I guess all have been taken), but the greater is the joy a maintained statsd library exists! And it even mentions Telegraf, which I'd like to use ❤️ 

The only thing I'm missing is a TCP connection support as laid out in https://github.com/sivy/node-statsd/pull/67. What would be the best way to help the TCP support to arrive?

I could obviously try to copy-paste @remie's PR to this repository, keeping him as the author of the commits, if that's the only thing missing and he agrees with it...

**Comment by bdeitte** [comment]
If you brought over that PR, that sounds great.  I don't think copy-pasting the code over will work exactly, as there has been some splitting of the one main file into more than one here.  But it shouldn't be too much extra work.  While I am not actively developing in this project, I'm quick to review and merge things in.

And you are right as mentioned in that other PR- this hasn't brought into this project yet.  There is another related outstanding issue as well with https://github.com/brightcove/hot-shots/issues/53
