### ISSUE TITLE
Tag values can only be strings. 

### ISSUE THREAD

**Issue by alex-gokkun** [brightcove/hot-shots#84]
https://github.com/brightcove/hot-shots/blob/46aa12c164508857a15ca7f394be4d99affd7025/types.d.ts#L4

Since it's possible to send different non-string tag values (e.g. booleans) I've been wondering if the Tag type should be updated accordingly.

**Comment by bdeitte** [comment]
All non-string values are coerced to strings, though, so I wonder if this makes sense as-is.  Not sure what is normally done in typescript types here myself.

**Comment by alex-gokkun** [comment]
Same here🤷
Despite the fact that the values are coerced to strings, it doesn't undermine convenience it might bring in some cases. For instance, if a tag has boolean values, the associated datadog metric can be categorized based on the tag's values.

**Comment by bdeitte** [comment]
Given the backwards compatible issue at this point and potentially real use case here, we're not going to change this.  Thanks but closing out!
