### ISSUE TITLE
tag syntax does not work for graphite carbon collector

### ISSUE THREAD

**Issue by kevzettler** [brightcove/hot-shots#85]
When using tags with `hot-shots` statsd client. and passing the tags in as an object not an array. 

I get errors from graphite carbon collector.

```
21 Aug 22:56:06 - DEBUG: Bad line: 63418,host in msg "host.api.eventloop.latency.avg:0.16290699999999997|g|#pid:63418,host:localhost"
21 Aug 22:56:06 - DEBUG: Bad line: localhost in msg "host.api.eventloop.latency.avg:0.16290699999999997|g|#pid:63418,host:localhost"
21 Aug 22:56:06 - DEBUG: Bad line: 0.026295,g,#pid in msg "host.api.eventloop.latency.min:0.026295|g|#pid:63418,host:localhost"
21 Aug 22:56:06 - DEBUG: Bad line: 63418,host in msg "host.api.eventloop.latency.min:0.026295|g|#pid:63418,host:localhost"
21 Aug 22:56:06 - DEBUG: Bad line: localhost in msg "host.api.eventloop.latency.min:0.026295|g|#pid:63418,host:localhost"
21 Aug 22:56:06 - DEBUG: Bad line: 1.215466,g,#pid in msg "host.api.eventloop.latency.max:1.215466|g|#pid:63418,host:localhost"
```
The `hot-shots` tag syntax of `message#tag:value,tag2:value,tag3:value` differs from what the graphite docs showacase of `message;tag=value;tag2=value;`

https://graphite.readthedocs.io/en/latest/tags.html#carbon

**Comment by bdeitte** [comment]
I believe most people are using multiple tags with Datadog, which does use the comma separator.  

It's not clear to me what the standard here is for statsd.  From what I read, the standard statds implementation doesn't support multiple tags, but that the forks that do would use commas.  https://github.com/etsy/statsd/issues/567.  If you can point to a statsd implementation that does use semicolons, then this would be a good addition as a new option to allow.

**Comment by bdeitte** [comment]
Given I haven't heard back here, closing out.  Please feel free to open something new if you can clarify how you see this.  Thanks!
